"""m1_core_schema

Revision ID: 5f17c78ec8b5
Revises: 
Create Date: 2026-07-07 15:54:21.170525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '5f17c78ec8b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensions required by the schema below: pgcrypto for gen_random_uuid(),
    # postgis for the geography column on properties.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    # All domain enum types are created explicitly here rather than being
    # auto-managed per table, since every enum column below sets
    # create_type=False. This also creates enums not yet referenced by any
    # column in this migration (alert_frequency, order_status,
    # otp_purpose), whose tables are added in later migrations.
    op.execute("CREATE TYPE user_role AS ENUM ('client', 'broker', 'admin')")
    op.execute(
        "CREATE TYPE property_status AS ENUM "
        "('draft', 'pending', 'active', 'sold', 'rented', 'expired', 'rejected')"
    )
    op.execute("CREATE TYPE listing_type AS ENUM ('sale', 'rent', 'pg')")
    op.execute(
        "CREATE TYPE property_type AS ENUM "
        "('apartment', 'villa', 'independent_house', 'plot', 'office', 'shop', 'pg_colive')"
    )
    op.execute("CREATE TYPE furnishing AS ENUM ('unfurnished', 'semi_furnished', 'fully_furnished')")
    op.execute("CREATE TYPE verification_status AS ENUM ('unverified', 'pending', 'verified', 'rejected')")
    op.execute(
        "CREATE TYPE lead_status AS ENUM "
        "('new', 'contacted', 'site_visit', 'negotiation', 'closed_won', 'closed_lost')"
    )
    op.execute(
        "CREATE TYPE notification_type AS ENUM "
        "('property_alert', 'price_drop', 'lead_received', 'message', 'listing_status', 'system')"
    )
    op.execute("CREATE TYPE alert_frequency AS ENUM ('instant', 'daily', 'weekly')")
    op.execute("CREATE TYPE boost_tier AS ENUM ('basic', 'featured', 'premium')")
    op.execute("CREATE TYPE order_status AS ENUM ('created', 'paid', 'failed', 'refunded')")
    op.execute("CREATE TYPE media_type AS ENUM ('image', 'video')")
    op.execute("CREATE TYPE otp_purpose AS ENUM ('login', 'signup', 'broker_verification')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boost_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('tier', postgresql.ENUM('basic', 'featured', 'premium', name='boost_tier', create_type=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_days', sa.SmallInteger(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', postgresql.ENUM('client', 'broker', 'admin', name='user_role', create_type=False), server_default='client', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('ix_users_email_unique', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('broker_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rera_number', sa.String(length=50), nullable=True),
    sa.Column('verification_status', postgresql.ENUM('unverified', 'pending', 'verified', 'rejected', name='verification_status', create_type=False), server_default='unverified', nullable=False),
    sa.Column('verification_documents', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=True),
    sa.Column('experience_years', sa.SmallInteger(), nullable=True),
    sa.Column('specializations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('social_links', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('service_areas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rera_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('property_alert', 'price_drop', 'lead_received', 'message', 'listing_status', 'system', name='notification_type', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'read_at', sa.text('created_at DESC')], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('listing_type', postgresql.ENUM('sale', 'rent', 'pg', name='listing_type', create_type=False), nullable=False),
    sa.Column('property_type', postgresql.ENUM('apartment', 'villa', 'independent_house', 'plot', 'office', 'shop', 'pg_colive', name='property_type', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'pending', 'active', 'sold', 'rented', 'expired', 'rejected', name='property_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('maintenance_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deposit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_negotiable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('bhk', sa.SmallInteger(), nullable=True),
    sa.Column('bathrooms', sa.SmallInteger(), nullable=True),
    sa.Column('area_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('floor', sa.SmallInteger(), nullable=True),
    sa.Column('total_floors', sa.SmallInteger(), nullable=True),
    sa.Column('facing', sa.String(length=20), nullable=True),
    sa.Column('age_years', sa.SmallInteger(), nullable=True),
    sa.Column('furnishing', postgresql.ENUM('unfurnished', 'semi_furnished', 'fully_furnished', name='furnishing', create_type=False), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('locality', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('metro_distance_m', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('pg_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('price > 0', name='ck_properties_price_positive'),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_properties_active_published_at', 'properties', [sa.text('published_at DESC')], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_properties_broker_status', 'properties', ['broker_id', 'status'], unique=False)
    op.create_index('ix_properties_city_locality', 'properties', ['city', 'locality'], unique=False)
    op.create_index('ix_properties_location', 'properties', ['location'], unique=False, postgresql_using='gist')
    op.create_index('ix_properties_price', 'properties', ['price'], unique=False)
    op.create_index('ix_properties_status_listing_type', 'properties', ['status', 'listing_type'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_client_broker_property_unique', 'conversations', ['client_id', 'broker_id', sa.text("COALESCE(property_id, '00000000-0000-0000-0000-000000000000'::uuid)")], unique=True)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('new', 'contacted', 'site_visit', 'negotiation', 'closed_won', 'closed_lost', name='lead_status', create_type=False), server_default='new', nullable=False),
    sa.Column('source', sa.String(length=30), server_default=sa.text("'enquiry'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_broker_status_created', 'leads', ['broker_id', 'status', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_leads_property', 'leads', ['property_id'], unique=False)
    op.create_table('property_media',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('media_type', postgresql.ENUM('image', 'video', name='media_type', create_type=False), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('stream_uid', sa.String(length=255), nullable=True),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_property_media_one_cover', 'property_media', ['property_id'], unique=True, postgresql_where=sa.text('is_cover = true'))
    op.create_index('ix_property_media_property_position', 'property_media', ['property_id', 'position'], unique=False)
    op.create_table('saved_properties',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'property_id')
    )
    op.create_index('ix_saved_properties_property', 'saved_properties', ['property_id'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_notes_lead', 'lead_notes', ['lead_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_lead_notes_lead', table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index('ix_saved_properties_property', table_name='saved_properties')
    op.drop_table('saved_properties')
    op.drop_index('ix_property_media_property_position', table_name='property_media')
    op.drop_index('ix_property_media_one_cover', table_name='property_media', postgresql_where=sa.text('is_cover = true'))
    op.drop_table('property_media')
    op.drop_index('ix_leads_property', table_name='leads')
    op.drop_index('ix_leads_broker_status_created', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_conversations_client_broker_property_unique', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_properties_status_listing_type', table_name='properties')
    op.drop_index('ix_properties_price', table_name='properties')
    op.drop_index('ix_properties_location', table_name='properties', postgresql_using='gist')
    op.drop_index('ix_properties_city_locality', table_name='properties')
    op.drop_index('ix_properties_broker_status', table_name='properties')
    op.drop_index('ix_properties_active_published_at', table_name='properties', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('properties')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('broker_profiles')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email_unique', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    op.drop_table('boost_plans')
    # ### end Alembic commands ###

    # create_type=False on every enum column means op.drop_table() above
    # does not remove these types automatically, so they are dropped
    # explicitly here. IF EXISTS is a defensive safety net.
    for enum_name in (
        "user_role",
        "property_status",
        "listing_type",
        "property_type",
        "furnishing",
        "verification_status",
        "lead_status",
        "notification_type",
        "alert_frequency",
        "boost_tier",
        "order_status",
        "media_type",
        "otp_purpose",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # Extensions are not dropped here: postgis and pgcrypto are
    # instance-level resources other schemas may depend on, and dropping
    # postgis cascades across every spatial type and function on the database.
